### ISSUE TITLE
oidc_settings dictionnary is not well formatted in the /etc/ood/config/ood_portal.yml

### ISSUE THREAD

**Issue by xpillons** [OSC/ood-ansible#115]
I'm using version 1.8 to setup Azure AD OIDC.
When trying to set the oidc variables in an override.yml file like that
```yml
oidc_remote_user_claim: upn
oidc_scope: 'openid profile email groups'
oidc_settings:
  OIDCPassIDTokenAs: serialized
  OIDCPassRefreshToken: On
  OIDCPassClaimsAs: environment
  OIDCStripCookies: 'mod_auth_openidc_session mod_auth_openidc_session_chunks mod_auth_openidc_session_0 mod_auth_openidc_session_1'
```
The settings are not well converted in proper yml format and the ansible playbook is returning this error
```
fatal: [ondemand]: FAILED! => {"changed": true, "cmd": "/opt/ood/ood-portal-generator/sbin/update_ood_portal --force", "delta": "0:00:00.353958", "end": "2021-07-02 14:02:28.243094", "msg": "non-zero return code", "rc": 1, "start": "2021-07-02 14:02:27.889136", "stderr": "(/etc/ood/config/ood_portal.yml): could not find expected ':' while scanning a simple key at line 364 column 1\nRun 'update_ood_portal --help' to see a full list of available options.", "stderr_lines": ["(/etc/ood/config/ood_portal.yml): could not find expected ':' while scanning a simple key at line 364 column 1", "Run 'update_ood_portal --help' to see a full list of available options."], "stdout": "", "stdout_lines": []}
```

Here is how the settings are written in the ood_portal.yml file
```
oidc_settings:
OIDCPassIDTokenAs serialized
OIDCPassRefreshToken True
OIDCPassClaimsAs environment
OIDCStripCookies 'mod_auth_openidc_session mod_auth_openidc_session_chunks mod_auth_openidc_session_0 mod_auth_openidc_session_1'
```

I've also noticed that the handler "update ood portal" is ignoring errors which shouldn't be the case, as here a malformed input should generate an error and not silently failed.

- How to define the oidc_settings so they are well formatted in the ppd_portal.yml file ?
- should the "update ood portal" failed be not ignored ?
