### ISSUE TITLE
How to limit ports used by bc_desktop apps ?

### ISSUE THREAD

**Issue by xpillons** [OSC/ood-ansible#124]
By default the bc_desktop app is using a very wide port range (2000-65535).
Looking at this documentation https://github.com/OSC/ood-documentation/blob/82e0a76d0cff81358d478aa589e2044f4b795bba/source/reference/files/submit-yml/basic-bc-options.rst it appears that there are options to change this range. Here is override.yml file content.  

```yml
      batch_connect:
        min_port: 61000
        max_port: 61010
        basic:
          min_port: 61000
          max_port: 61010
          script_wrapper: |
            module purge
            %s
        vnc:
          min_port: 61000
          max_port: 61010
          script_wrapper: |
            module purge
            export PATH="/opt/TurboVNC/bin:$PATH"
            export WEBSOCKIFY_CMD="/usr/bin/websockify"
            %s
``` 

I can see in the `/etc/ood/config/clusters.d/ondemand.yml` that the content is correct, however when I start a Remote Desktop session, this port range is not pickup. 
How to make sure these values are read and used to limit the port range ?
