### ISSUE TITLE
how to define multiple bc_desktop entries ?

### ISSUE THREAD

**Issue by xpillons** [OSC/ood-ansible#126]
I would like to be able to add several entries for bc_desktop on the same cluster, for example one GPU accelerated and one CPU like this : 
```yml
ood_apps:
  bc_desktop:
    title: "desktop 1"
  bc_desktop:
    title: "desktop 2"
```

but this looks not possible as I'm having this warning. 
 "[WARNING]: While constructing a mapping from /hpc/playbooks/ood-overrides.yml, line 36, column 3, found a duplicate dict key (bc_desktop). Using last defined value only."

How to add multiple entries here ?
