### ISSUE TITLE
ood_portal.yml permissions too strict

### ISSUE THREAD

**Issue by simonleary-umass-edu** [OSC/ood-ansible#156]
https://github.com/OSC/ood-ansible/blob/9dc82d7b4cae1ea40e6e83d81722d304c7164023/tasks/configure.yml#L22
mode: 'u=rw,g=r,o='

When I start my ondemand-dex service, I get permission denied on this file.
Is there a reason that the world shouldn't be able to read this config?

**Comment by simonleary-umass-edu** [comment]
whole code block:
```
- name: template ood_portal.yml
  template:
    src: "ood_portal.yml.j2"
    dest: "{{ ood_base_conf_dir }}/ood_portal.yml"
    mode: 'u=rw,g=r,o='
  notify: update ood portal
```
