### ISSUE TITLE
Changing app_root: settings in nginx_stage.yml

### ISSUE THREAD

**Issue by sandermitre** [OSC/ood-ansible#219]
Looking at the Jinja template this doesn't look changeable. Is there another way to do it?

If we can agree on a variable name e.g. app_root_dev I can create a pull request if that's what's needed.

**Comment by johrstrom** [comment]
> If we can agree on a variable name e.g. app_root_dev I can create a pull request if that's what's needed.

That sounds just fine to me, using the same name that the upstream uses.

**Comment by sandermitre** [comment]
My mistake you can set it already the variable logic is just a little different than the other if statements.


```
    nginx_app_root:
      dev: '~%{owner}/%{portal}/dev/%{name}'
      usr: '/var/www/ood/apps/usr/%{owner}/gateway/%{name}'
      sys: '/var/www/ood/apps/sys/%{name}'
```
