### ISSUE TITLE
Extend role to allow deployment of assets into `/var/www/ood/public/`

### ISSUE THREAD

**Issue by mikej888** [OSC/ood-ansible#241]
For example, site-specific logos.

This can be done in a playbook, for example
```yaml
  vars:
    # Assets directory whose contents are to be copied to
    # /var/www/ood/public/.
    # local_public_assets: files/public
    # Templates directory.
    local_templates: "templates/"
  tasks:
    - name: Copy 'public' assets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/var/www/ood/public"
        owner: root
        group: root
      with_fileglob: "{{ local_public_assets }}/*"
      when: local_public_assets is defined
```
For role completeness, it would be useful if it could be done via the role. Thanks,
