### ISSUE TITLE
Strange formatting in clusters with multiline yaml (|) in clusters

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#54]
When I configure a cluster like so
```yaml
clusters:
  titan:
    v2:
      batch_connect:
        vnc:
          script_wrapper: |
            #!/bin/bash
        basic:
          script_wrapper: |
            #!/bin/bash
```
It turns out to get written like this, which may or may not be OK, it does look off and perhaps could be wrong if there are several lines. 
```yaml
v2:
    batch_connect:
        basic:
            script_wrapper: '#!/bin/bash

                '
        vnc:
            script_wrapper: '#!/bin/bash

                '
```
