### ISSUE TITLE
bc_desktop app fails to connect

### ISSUE THREAD

**Issue by miketice22** [OSC/ood-ansible#78]
When launching the DeepOps desktop in Open OnDemand, it fails to connect. When looking at the output.log I see a ton of these errors:
```
(dconf:243965): dconf-CRITICAL **: 13:20:22.363: unable to create directory '/run/user/20199891/dconf': Permission denied.  dconf will not work properly.
mate-session[243970]: dconf-CRITICAL: unable to create directory '/run/user/20199891/dconf': Permission denied.  dconf will not work properly.
```
However, I can manually create that directory with the user that launches the Desktop. Also, even with that directory already existing I still get this error when launching the desktop from OOD.

I also get the same error when trying to launch a xfce desktop as well.

Any ideas why this is happening?

```
# cat /etc/ood/config/apps/bc_desktop/deepops.yml 
---
title: "NVIDIA DeepOps Desktop"
cluster: "deepops"
submit: "submit/deepops_desktop.yml.erb"
attributes:
  desktop: "xfce"
  bc_queue: null
  bc_account: null
  bc_num_gpus:
    label: "Number of GPUs"
    value: 1
```

**Comment by johrstrom** [comment]
We recently switched to Slurm and for whatever reason we had to start setting `XDG_RUNTIME_DIR`. 

You can see how we do it here in the `batch_connect.before_script` portion of our `script.yml`.

https://github.com/OSC/osc-ood-config/blob/d86c19e6b4a2742300666e539b4f236c9476b5bc/ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb#L50-L56

**Comment by miketice22** [comment]
Thanks, not sure what part of this output is relevant, but now I get a different error at the end.
```
Setting VNC password...
Starting VNC server...

Warning: apl-redd-ai02.datalake.jhuapl.edu:1 is taken because of /tmp/.X1-lock
Remove this file if there is no X server apl-redd-ai02.datalake.jhuapl.edu:1
Killing Xvnc process ID 268396
Xvnc process ID 268396 already killed
Xvnc did not appear to shut down cleanly. Removing /tmp/.X11-unix/X1
Xvnc did not appear to shut down cleanly. Removing /tmp/.X1-lock

Desktop 'TurboVNC: apl-redd-ai02.datalake.jhuapl.edu:1 (ticemp1)' started on display apl-redd-ai02.datalake.jhuapl.edu:1

Log file is vnc.log
Successfully started VNC server on apl-redd-ai02.datalake.jhuapl.edu:5901...
Script starting...
Starting websocket server...
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

Launching desktop 'mate'...
WebSocket server settings:
  - Listen on :3339
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
Scanning VNC log file for user authentications...
Generating connection YAML file...
cat: /etc/xdg/autostart/gnome-keyring-gpg.desktop: No such file or directory
cat: /etc/xdg/autostart/rhsm-icon.desktop: No such file or directory
generating cookie with syscall
generating cookie with syscall
generating cookie with syscall
generating cookie with syscall
mate-session[269439]: WARNING: Could not parse desktop file /home/ticemp1/.config/autostart/gnome-keyring-gpg.desktop: Key file does not start with a group
mate-session[269439]: GLib-GObject-CRITICAL: object GsmAutostartApp 0x1dce320 finalized while still in-construction
mate-session[269439]: GLib-GObject-CRITICAL: Custom constructor for class GsmAutostartApp returned NULL (which is invalid). Please use GInitable instead.
mate-session[269439]: WARNING: could not read /home/ticemp1/.config/autostart/gnome-keyring-gpg.desktop
mate-session[269439]: WARNING: Could not parse desktop file /home/ticemp1/.config/autostart/rhsm-icon.desktop: Key file does not start with a group
mate-session[269439]: GLib-GObject-CRITICAL: object GsmAutostartApp 0x1dce590 finalized while still in-construction
mate-session[269439]: GLib-GObject-CRITICAL: Custom constructor for class GsmAutostartApp returned NULL (which is invalid). Please use GInitable instead.
mate-session[269439]: WARNING: could not read /home/ticemp1/.config/autostart/rhsm-icon.desktop
SELinux Troubleshooter: Applet requires SELinux be enabled to run.
vmware-user: could not open /proc/fs/vmblock/dev
/usr/share/system-config-printer/applet.py:44: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.1091" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
*** ERROR ***
TI:16:01:59	TH:0x2322660	FI:gpm-manager.c	FN:gpm_manager_systemd_inhibit,1784
 - Error in dbus - GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
Traceback:
	mate-power-manager() [0x418b9f]
	mate-power-manager() [0x411220]
	/lib64/libgobject-2.0.so.0(g_type_create_instance+0x1fb) [0x7f1a6d2675db]
	/lib64/libgobject-2.0.so.0(+0x152dd) [0x7f1a6d24b2dd]
	/lib64/libgobject-2.0.so.0(g_object_new_with_properties+0x27d) [0x7f1a6d24cb8d]
	/lib64/libgobject-2.0.so.0(g_object_new+0xc1) [0x7f1a6d24d571]
	mate-power-manager() [0x411a22]
	mate-power-manager() [0x4080b8]
	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f1a6c656555]
	mate-power-manager() [0x4083db]
Initializing caja-image-converter extension
Initializing caja-open-terminal extension
```

**Comment by johrstrom** [comment]
It's the `mate-power-manager` that's problematic with mulit-user systems (It's that panel to stop/restart the machine). 

An easy fix is to simply remove the package.  You could also set the dbus policies up to allow folks to see it (though I assume other measures kick in so they can't stop/restart the machine) - though I don't know how to do this.

**Comment by miketice22** [comment]
Now, network manager?
```
*** ERROR ***
TI:16:11:16	TH:0x2206660	FI:gpm-manager.c	FN:gpm_manager_systemd_inhibit,1784
 - Error in dbus - GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
Traceback:
	mate-power-manager() [0x418b9f]
	mate-power-manager() [0x411220]
	/lib64/libgobject-2.0.so.0(g_type_create_instance+0x1fb) [0x7f38da17f5db]
	/lib64/libgobject-2.0.so.0(+0x152dd) [0x7f38da1632dd]
	/lib64/libgobject-2.0.so.0(g_object_new_with_properties+0x27d) [0x7f38da164b8d]
	/lib64/libgobject-2.0.so.0(g_object_new+0xc1) [0x7f38da165571]
	mate-power-manager() [0x411a22]
	mate-power-manager() [0x4080b8]
	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f38d956e555]
	mate-power-manager() [0x4083db]
/usr/share/system-config-printer/applet.py:44: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.1160" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file
Initializing caja-image-converter extension
Initializing caja-open-terminal extension

(nm-applet:272300): nm-applet-WARNING **: 16:11:16.334: GDBus.Error:org.freedesktop.NetworkManager.AgentManager.PermissionDenied: An agent with this ID is already registered for this user.
```

**Comment by johrstrom** [comment]
Seems like stuff started on the backend OK.  I'd imagine you'd have to check your `ood_portal.yml` configs at this point. 

Specifically these that deal with rewriting to that url (these are the defaults).
```yaml
use_rewrites: false
node_uri: '/node'
rnode_uri: '/rnode'
host_regex: '[^/]+'
```

**Comment by miketice22** [comment]
```
# cat /etc/ood/config/ood_portal.yml
# Ansible managed
---
servername: ondemand.jhuapl.edu
port: '443'

ssl:
- 'SSLCertificateFile /etc/pki/tls/certs/aplcdhen01.jhuapl.edu.pem'
- 'SSLCertificateKeyFile /etc/pki/tls/private/aplcdhen01.jhuapl.edu.key'
- 'SSLCertificateChainFile /etc/pki/tls/certs/aplcdhen01.jhuapl.edu.pem'

auth:
- 'AuthType openid-connect'
- 'Require valid-user'

dex:
  client_secret: 334389048b872a533002b34d73f8c29fd09efc50
  connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: aplid.jhuapl.edu:636
        insecureSkipVerify: false
        userSearch:
          baseDN: cn=users,dc=jhuapl,dc=edu
          filter: "(objectClass=person)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: displayName
          preferredUsernameAttr: uid
        groupSearch:
          baseDN: ou=Groups,dc=dom1-proxy,dc=apl-staging
          filter: "(objectClass=group)"
          userMatchers:
            - userAttr: DN
              groupAttr: member
          nameAttr: cn
  frontend:
    theme: ondemand
```

**Comment by johrstrom** [comment]
Yea I think you need to flip `use_rewrites: false` to true (apparently we call it `httpd_use_rewrites` in ansible). Otherwise, everything like that will be 404 because we don't allow redirects.

After that you could probably set `host_regex: '[\w.-]+\.datalake\.jhuapl\.edu'` for a little extra security (so you don't allow redirects outside you're site).

**Comment by miketice22** [comment]
```
# cat /etc/ood/config/ood_portal.yml
# Ansible managed
---
servername: ondemand.jhuapl.edu
port: '443'

ssl:
- 'SSLCertificateFile /etc/pki/tls/certs/aplcdhen01.jhuapl.edu.pem'
- 'SSLCertificateKeyFile /etc/pki/tls/private/aplcdhen01.jhuapl.edu.key'
- 'SSLCertificateChainFile /etc/pki/tls/certs/aplcdhen01.jhuapl.edu.pem'

use_rewrites: true
host_regex: '[\w.-]+\.datalake\.jhuapl\.edu'

auth:
- 'AuthType openid-connect'
- 'Require valid-user'

dex:
  client_secret: 334389048b872a533002b34d73f8c29fd09efc50
  connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: aplid.jhuapl.edu:636
        insecureSkipVerify: false
        userSearch:
          baseDN: cn=users,dc=jhuapl,dc=edu
          filter: "(objectClass=person)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: displayName
          preferredUsernameAttr: uid
        groupSearch:
          baseDN: ou=Groups,dc=dom1-proxy,dc=apl-staging
          filter: "(objectClass=group)"
          userMatchers:
            - userAttr: DN
              groupAttr: member
          nameAttr: cn
  frontend:
    theme: ondemand
[root@aplcdhen01 ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal -f
cp -p /etc/pki/tls/certs/aplcdhen01.jhuapl.edu.pem /etc/ood/dex/aplcdhen01.jhuapl.edu.pem
chown ondemand-dex:ondemand-dex /etc/ood/dex/aplcdhen01.jhuapl.edu.pem
cp -p /etc/pki/tls/private/aplcdhen01.jhuapl.edu.key /etc/ood/dex/aplcdhen01.jhuapl.edu.key
chown ondemand-dex:ondemand-dex /etc/ood/dex/aplcdhen01.jhuapl.edu.key
No change in Apache config.
No change in the Dex config.
Completed successfully!
```

Still the same thing, did I make the change incorrectly / in the wrong place?
